### ISSUE TITLE
Don't mix files with salt states

### ISSUE THREAD

**Issue by herisanu** [bmihaescu/systems#1]
Please [1] keep states separately from files. For this project we'll not use salt environments.

Proposed directory structure:
```
build
build/saltstack/etc - configuration files (are they really necesary? you know the saltmaster and the DNS hostnames should be set for each host AFAIK)
build/saltstack/keys - pre-shared salt keys
salt - salt states
pillar - salt pillar
```

Keep pushing often. I'm a watcher so i can provide feedback.

[1] https://github.com/bmihaescu/systems/blob/master/saltstack/salt/prod/loadbalancer/haproxy/haproxy.cfg

**Comment by bmihaescu** [comment]
I will push how often I will work on it. I have a full period at the office
too.
Thanks for suggestions.
I need the config files for the minions to appear with the hostname on the
master accepted minions list.



2017-06-12 10:51 GMT+03:00 herisanu <notifications@github.com>:
